DRDT-107 : Porting Nativo Plugin
fariasf/drdt-test pull request #76
Opened 2019-02-20 13:45 UTC by akhan3051

2019-02-20 13:50 UTC, fariasf commented
Created new staging environment for pr-76. Here are some useful links:

[WordPress Admin](https://pr-76-drdt.pantheonsite.io/wp/wp-admin)

[Homepage](https://pr-76-drdt.pantheonsite.io/)
[Article](https://pr-76-drdt.pantheonsite.io/jobsite-tips/abandoned-cable-removal/)
[Listicle](https://pr-76-drdt.pantheonsite.io/jobsite-tips/exterior/12-scaffolding-safety-tips-and-handy-hints/)
[Page](https://pr-76-drdt.pantheonsite.io/about-construction-pro-tips/)
[Hub](https://pr-76-drdt.pantheonsite.io/jobsite-tips/)

2019-02-20 13:51 UTC, fariasf commented
There are visual regressions! 

View the [full visual regression test report](https://circleci.com/gh/fariasf/drdt-test/2553/artifacts/0/artifacts/backstop_data/html_report/index.html)

2019-02-20 13:53 UTC, fariasf commented
Updated staging environment for pr-76. Here are some useful links:

[WordPress Admin](https://pr-76-drdt.pantheonsite.io/wp/wp-admin)

[Homepage](https://pr-76-drdt.pantheonsite.io/)
[Article](https://pr-76-drdt.pantheonsite.io/jobsite-tips/abandoned-cable-removal/)
[Listicle](https://pr-76-drdt.pantheonsite.io/jobsite-tips/exterior/12-scaffolding-safety-tips-and-handy-hints/)
[Page](https://pr-76-drdt.pantheonsite.io/about-construction-pro-tips/)
[Hub](https://pr-76-drdt.pantheonsite.io/jobsite-tips/)

2019-02-20 13:54 UTC, fariasf commented
There are visual regressions! 

View the [full visual regression test report](https://circleci.com/gh/fariasf/drdt-test/2563/artifacts/0/artifacts/backstop_data/html_report/index.html)

2019-02-20 13:55 UTC, fariasf commented
Congrats! Frontend performance tests passed!

Full Lighthouse performance results:

| Page/Branch | pr-76 | master | Result |
| --- | ---: | ---: | :---: |
| Homepage | [97](https://circleci.com/gh/fariasf/drdt-test/2562/artifacts/0/artifacts/lighthouse_results/pr-76/homepage/lighthouse.report.html) | [96](https://circleci.com/gh/fariasf/drdt-test/2562/artifacts/0/artifacts/lighthouse_results/master/homepage/lighthouse.report.html) | ✔ |
| Article | [98](https://circleci.com/gh/fariasf/drdt-test/2562/artifacts/0/artifacts/lighthouse_results/pr-76/article/lighthouse.report.html) | [97](https://circleci.com/gh/fariasf/drdt-test/2562/artifacts/0/artifacts/lighthouse_results/master/article/lighthouse.report.html) | ✔ |
| Listicle | [98](https://circleci.com/gh/fariasf/drdt-test/2562/artifacts/0/artifacts/lighthouse_results/pr-76/listicle/lighthouse.report.html) | [98](https://circleci.com/gh/fariasf/drdt-test/2562/artifacts/0/artifacts/lighthouse_results/master/listicle/lighthouse.report.html) | ✔ |
| Page | [98](https://circleci.com/gh/fariasf/drdt-test/2562/artifacts/0/artifacts/lighthouse_results/pr-76/page/lighthouse.report.html) | [98](https://circleci.com/gh/fariasf/drdt-test/2562/artifacts/0/artifacts/lighthouse_results/master/page/lighthouse.report.html) | ✔ |
| Hub | [97](https://circleci.com/gh/fariasf/drdt-test/2562/artifacts/0/artifacts/lighthouse_results/pr-76/hub/lighthouse.report.html) | [95](https://circleci.com/gh/fariasf/drdt-test/2562/artifacts/0/artifacts/lighthouse_results/master/hub/lighthouse.report.html) | ✔ |


(**Note: Tests are against the _NOADS_ version of the pages!**)

2019-02-20 15:45 UTC, fariasf requested changes
This PR seems to have issues with the `.gitignore`. It includes a bunch of plugins not related to Nativo. Please fix before review. Thanks!

2019-02-20 22:37 UTC, fariasf commented on web/wp-content/plugins/tmbi-nativo/inc/class-tmbi-nativo-in-articles.php
> +		if ( 3 === $paragraph_number && 100 >= $word_count ) {
The `3` here seems to reference the `CADENCE` constant?

2019-02-20 22:38 UTC, fariasf commented on web/wp-content/plugins/tmbi-nativo/inc/class-tmbi-nativo-in-articles.php
> +			'flag'       => $flag,
There's no need to return a `flag` - returning either the `$nativo_ad_tag` or `null`/`false` should be enough.

2019-02-20 22:42 UTC, fariasf commented on web/wp-content/plugins/tmbi-nativo/class-tmbi-nativo.php
> +	public function __construct() {
I think there's no need to instantiate the class if all the action happens here in the constructor. I've seen how instantiating the class results in extra opcode, compared to just adding the filters outside the class (and referencing the functions like `array( 'TMBI_Nativo', 'register_nativo_post_type' )`) but I'm not sure if it has a performance impact. I'll create a ticket to review and confirm!

2019-02-21 10:53 UTC, fariasf commented
Updated staging environment for pr-76. Here are some useful links:

[WordPress Admin](https://pr-76-drdt.pantheonsite.io/wp/wp-admin)

[Homepage](https://pr-76-drdt.pantheonsite.io/)
[Article](https://pr-76-drdt.pantheonsite.io/jobsite-tips/abandoned-cable-removal/)
[Listicle](https://pr-76-drdt.pantheonsite.io/jobsite-tips/exterior/12-scaffolding-safety-tips-and-handy-hints/)
[Page](https://pr-76-drdt.pantheonsite.io/about-construction-pro-tips/)
[Hub](https://pr-76-drdt.pantheonsite.io/jobsite-tips/)

2019-02-21 10:54 UTC, fariasf commented
There are visual regressions! 

View the [full visual regression test report](https://circleci.com/gh/fariasf/drdt-test/2692/artifacts/0/artifacts/backstop_data/html_report/index.html)

2019-02-21 10:55 UTC, fariasf commented
Congrats! Frontend performance tests passed!

Full Lighthouse performance results:

| Page/Branch | pr-76 | master | Result |
| --- | ---: | ---: | :---: |
| Homepage | [95](https://circleci.com/gh/fariasf/drdt-test/2691/artifacts/0/artifacts/lighthouse_results/pr-76/homepage/lighthouse.report.html) | [96](https://circleci.com/gh/fariasf/drdt-test/2691/artifacts/0/artifacts/lighthouse_results/master/homepage/lighthouse.report.html) | ✔ |
| Article | [98](https://circleci.com/gh/fariasf/drdt-test/2691/artifacts/0/artifacts/lighthouse_results/pr-76/article/lighthouse.report.html) | [98](https://circleci.com/gh/fariasf/drdt-test/2691/artifacts/0/artifacts/lighthouse_results/master/article/lighthouse.report.html) | ✔ |
| Listicle | [97](https://circleci.com/gh/fariasf/drdt-test/2691/artifacts/0/artifacts/lighthouse_results/pr-76/listicle/lighthouse.report.html) | [97](https://circleci.com/gh/fariasf/drdt-test/2691/artifacts/0/artifacts/lighthouse_results/master/listicle/lighthouse.report.html) | ✔ |
| Page | [98](https://circleci.com/gh/fariasf/drdt-test/2691/artifacts/0/artifacts/lighthouse_results/pr-76/page/lighthouse.report.html) | [98](https://circleci.com/gh/fariasf/drdt-test/2691/artifacts/0/artifacts/lighthouse_results/master/page/lighthouse.report.html) | ✔ |
| Hub | [97](https://circleci.com/gh/fariasf/drdt-test/2691/artifacts/0/artifacts/lighthouse_results/pr-76/hub/lighthouse.report.html) | [94](https://circleci.com/gh/fariasf/drdt-test/2691/artifacts/0/artifacts/lighthouse_results/master/hub/lighthouse.report.html) | ✔ |


(**Note: Tests are against the _NOADS_ version of the pages!**)

2019-02-21 11:16 UTC, fariasf commented
Updated staging environment for pr-76. Here are some useful links:

[WordPress Admin](https://pr-76-drdt.pantheonsite.io/wp/wp-admin)

[Homepage](https://pr-76-drdt.pantheonsite.io/)
[Article](https://pr-76-drdt.pantheonsite.io/jobsite-tips/abandoned-cable-removal/)
[Listicle](https://pr-76-drdt.pantheonsite.io/jobsite-tips/exterior/12-scaffolding-safety-tips-and-handy-hints/)
[Page](https://pr-76-drdt.pantheonsite.io/about-construction-pro-tips/)
[Hub](https://pr-76-drdt.pantheonsite.io/jobsite-tips/)

2019-02-21 11:17 UTC, fariasf commented
There are visual regressions! 

View the [full visual regression test report](https://circleci.com/gh/fariasf/drdt-test/2701/artifacts/0/artifacts/backstop_data/html_report/index.html)

2019-02-21 11:19 UTC, fariasf commented
Congrats! Frontend performance tests passed!

Full Lighthouse performance results:

| Page/Branch | pr-76 | master | Result |
| --- | ---: | ---: | :---: |
| Homepage | [95](https://circleci.com/gh/fariasf/drdt-test/2702/artifacts/0/artifacts/lighthouse_results/pr-76/homepage/lighthouse.report.html) | [96](https://circleci.com/gh/fariasf/drdt-test/2702/artifacts/0/artifacts/lighthouse_results/master/homepage/lighthouse.report.html) | ✔ |
| Article | [98](https://circleci.com/gh/fariasf/drdt-test/2702/artifacts/0/artifacts/lighthouse_results/pr-76/article/lighthouse.report.html) | [97](https://circleci.com/gh/fariasf/drdt-test/2702/artifacts/0/artifacts/lighthouse_results/master/article/lighthouse.report.html) | ✔ |
| Listicle | [98](https://circleci.com/gh/fariasf/drdt-test/2702/artifacts/0/artifacts/lighthouse_results/pr-76/listicle/lighthouse.report.html) | [98](https://circleci.com/gh/fariasf/drdt-test/2702/artifacts/0/artifacts/lighthouse_results/master/listicle/lighthouse.report.html) | ✔ |
| Page | [98](https://circleci.com/gh/fariasf/drdt-test/2702/artifacts/0/artifacts/lighthouse_results/pr-76/page/lighthouse.report.html) | [98](https://circleci.com/gh/fariasf/drdt-test/2702/artifacts/0/artifacts/lighthouse_results/master/page/lighthouse.report.html) | ✔ |
| Hub | [97](https://circleci.com/gh/fariasf/drdt-test/2702/artifacts/0/artifacts/lighthouse_results/pr-76/hub/lighthouse.report.html) | [94](https://circleci.com/gh/fariasf/drdt-test/2702/artifacts/0/artifacts/lighthouse_results/master/hub/lighthouse.report.html) | ✔ |


(**Note: Tests are against the _NOADS_ version of the pages!**)

2019-02-21 11:33 UTC, akhan3051 commented
@fariasf, I have done the requested changes. Please take a look, when you have some time.

2019-03-01 17:50 UTC, fariasf commented
#105 removes the whitespace issues

2019-03-01 17:50 UTC, closed without merging